# Variables

In [1]:
edad = 20
nombre = 'Pablito'
print(edad)
print(nombre)
print(f'El usuario se llama: {nombre} y tiene {edad} años.')

20
Pablito
El usuario se llama: Pablito y tiene 20 años.

In [2]:
print(type(1))
print(type('strings'))
print(type(1.5))

<class 'int'>
<class 'str'>
<class 'float'>

# Strings

In [3]:
strUsuario = 'Ana'
print(strUsuario)
strUsuario = "O'Brian"
print(strUsuario)

Ana
O'Brian

# Listas

In [4]:
lista_vacia = []
lista_vacia

[]

In [5]:
lista_vacia.append('Valor agregado 1')
lista_vacia

['Valor agregado 1']

In [6]:
lista_super = ['Leche', 'Cereal', 'Pollo', 'Carne de res', 'Pescado']
lista_super

['Leche', 'Cereal', 'Pollo', 'Carne de res', 'Pescado']

# Dictionaries

In [7]:
dictWithBrackets = {'Nombre1': 'Valor1', 'Nombre2': 'Valor2', 'Nombre3': 3}
print(dictWithBrackets)

dictWithDict = dict(Nombre4 = 'Valor4', Nombre5 = 5, Nombre6 = 6.)
print(dictWithDict)
print(type(dictWithBrackets))
print(type(dictWithDict))

{'Nombre1': 'Valor1', 'Nombre2': 'Valor2', 'Nombre3': 3}
{'Nombre4': 'Valor4', 'Nombre5': 5, 'Nombre6': 6.0}
<class 'dict'>
<class 'dict'>

In [8]:
# Para extraer valores, se hace en forma de arbol, es decir, para extraer "Valor de prueba 2" 
# se selecciona por [], en este caso sería dictMixto['Nombre6']['prueba2']

dictMixto = dict(Nombre4 = 'Valor4', Nombre5 = 5, Nombre6 = dict(prueba1 = 2, prueba2 = 'Valor de prueba 2'))
dictMixto

{'Nombre4': 'Valor4',
 'Nombre5': 5,
 'Nombre6': {'prueba1': 2, 'prueba2': 'Valor de prueba 2'}}

In [9]:
# Extrae el valor en Nombre4
dictMixto['Nombre4']

'Valor4'

In [10]:
# Esto generara un error ya que no existe ningun valor llamado prueba3 en la sección Nombre6
dictMixto['Nombre6']['prueba3']

KeyError: 'prueba3'

In [11]:
var1 = 'Nombre6'
var2 = 'prueba2'
dictMixto[var1][var2]

'Valor de prueba 2'

# Importar Librerias

In [12]:
# Se pueden designar alias a las librerias para mejor lectura y referencia
import os, sys
import pandas as pd
import numpy as np

In [13]:
# Lee CSV
datos = pd.read_csv(r"Estadistica_2026.csv")

In [14]:
# Muestra información de la lectura
datos

,encuesta,encuestador,sexo,edad,entidad,facultad,turno,tipo_transporte,gasto_transporte,gasto_comida,...,cercania_transporte,numero_transporte,promedio,actividad_extra,tiempo_descanso,ausencia_recursos,fuente_ingresos,frecuencia_retardos,apoyo_transporte,impacto_transporte
0,1,3,2,19,10,3,2,1,4,1,...,1,1,4,2,4,2,1,2,2,2
1,2,16,1,19,14,3,3,1,1,1,...,1,2,2,2,4,2,1,3,1,1
2,3,8,1,20,17,3,2,3,1,3,...,1,1,3,2,4,2,1,1,4,2
3,4,16,1,19,10,3,2,1,1,4,...,2,2,2,2,4,2,2,2,1,1
4,5,47,1,23,4,10,3,1,1,5,...,1,2,3,2,2,2,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2081,30,1,21,7,7,2,1,3,4,...,2,2,2,2,3,1,1,4,1,1
2081,2082,30,1,23,4,7,2,3,4,2,...,1,1,3,1,4,2,1,1,1,2
2082,2083,35,1,19,9,9,1,3,4,4,...,1,1,4,2,4,2,2,1,3,2
2083,2084,43,1,23,13,3,3,4,3,5,...,4,1,3,1,3,2,2,3,1,1
2084,2085,35,1,50,7,3,3,1,4,5,...,2,4,3,1,4,1,3,1,1,1

In [15]:
# Muestra tipo de datos
type(datos)

pandas.DataFrame

In [16]:
# Genera un primer analisis general del contenido del dataframe
datos.describe()

,encuesta,encuestador,sexo,edad,entidad,facultad,turno,tipo_transporte,gasto_transporte,gasto_comida,...,cercania_transporte,numero_transporte,promedio,actividad_extra,tiempo_descanso,ausencia_recursos,fuente_ingresos,frecuencia_retardos,apoyo_transporte,impacto_transporte
count,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,...,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000,2085.000000
mean,1043.000000,23.936691,1.483933,21.708393,8.578897,6.098321,1.972182,2.012470,2.426859,2.601918,...,1.611511,1.934293,2.938129,1.596163,2.974580,1.865707,1.317506,2.705516,1.600959,1.428777
std,602.031976,13.777810,0.499862,2.976451,4.563913,3.166891,0.791142,1.106965,1.306652,1.334899,...,0.797466,0.864639,0.781571,0.490783,0.927727,0.341048,0.547990,1.191216,1.022304,0.495020
min,1.000000,1.000000,1.000000,17.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,522.000000,12.000000,1.000000,20.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000
50%,1043.000000,24.000000,1.000000,21.000000,8.000000,6.000000,2.000000,2.000000,2.000000,2.000000,...,1.000000,2.000000,3.000000,2.000000,3.000000,2.000000,1.000000,3.000000,1.000000,1.000000
75%,1564.000000,36.000000,2.000000,23.000000,12.000000,9.000000,3.000000,3.000000,4.000000,4.000000,...,2.000000,2.000000,3.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000,2.000000
max,2085.000000,47.000000,2.000000,56.000000,17.000000,11.000000,3.000000,4.000000,4.000000,5.000000,...,4.000000,4.000000,4.000000,2.000000,4.000000,2.000000,3.000000,4.000000,4.000000,2.000000

In [17]:
# Muestra el tipo de datos contenidos 
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 2085 entries, 0 to 2084
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   encuesta              2085 non-null   int64
 1   encuestador           2085 non-null   int64
 2   sexo                  2085 non-null   int64
 3   edad                  2085 non-null   int64
 4   entidad               2085 non-null   int64
 5   facultad              2085 non-null   int64
 6   turno                 2085 non-null   int64
 7   tipo_transporte       2085 non-null   int64
 8   gasto_transporte      2085 non-null   int64
 9   gasto_comida          2085 non-null   int64
 10  presupuesto_semana    2085 non-null   int64
 11  tiempo_transporte     2085 non-null   int64
 12  actividad_transporte  2085 non-null   int64
 13  cercania_transporte   2085 non-null   int64
 14  numero_transporte     2085 non-null   int64
 15  promedio              2085 non-null   int64
 16  actividad_extra       2085 non-null   int64
 17  tiempo_descanso       2085 non-null   int64
 18  ausencia_recursos     2085 non-null   int64
 19  fuente_ingresos       2085 non-null   int64
 20  frecuencia_retardos   2085 non-null   int64
 21  apoyo_transporte      2085 non-null   int64
 22  impacto_transporte    2085 non-null   int64
dtypes: int64(23)
memory usage: 374.8 KB

In [18]:
# Análisis sobre columnas seleccionadas
datos[['sexo', 'edad', 'entidad']].describe()

              sexo         edad      entidad
count  2085.000000  2085.000000  2085.000000
mean      1.483933    21.708393     8.578897
std       0.499862     2.976451     4.563913
min       1.000000    17.000000     1.000000
25%       1.000000    20.000000     5.000000
50%       1.000000    21.000000     8.000000
75%       2.000000    23.000000    12.000000
max       2.000000    56.000000    17.000000

In [19]:
# Tipo de datos sobre columnas seleccionadas
datos[['sexo', 'edad', 'entidad']].info()

<class 'pandas.DataFrame'>
RangeIndex: 2085 entries, 0 to 2084
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sexo     2085 non-null   int64
 1   edad     2085 non-null   int64
 2   entidad  2085 non-null   int64
dtypes: int64(3)
memory usage: 49.0 KB

In [20]:
# Se pueden agregar datos por columnas de manera rapida
datos['edad'].sum()

np.int64(45262)

In [21]:
datos[['sexo', 'edad', 'entidad']].median()

sexo        1.0
edad       21.0
entidad     8.0
dtype: float64

In [22]:
# Para poder filtrar se pueden dar condiciones, como ejemplo que entidad sea = a 10
print((datos['entidad'] == 10))
# Cual es el valor del resultado de comparar entidad con el valor 10 en la posición 4
print((datos['entidad'] == 10)[3])
# Tipo de dato resultado de comparar entidad con el valor 10 en la posición 4
type((datos['entidad'] == 10)[3])

0        True
1       False
2       False
3        True
4       False
        ...
2080    False
2081    False
2082    False
2083    False
2084    False
Name: entidad, Length: 2085, dtype: bool
True

numpy.bool

In [23]:
# Valores unicos de la columna
datos['edad'].unique()

datos['edad'].describe()

count    2085.000000
mean       21.708393
std         2.976451
min        17.000000
25%        20.000000
50%        21.000000
75%        23.000000
max        56.000000
Name: edad, dtype: float64

In [24]:
# Las comparaciones son:
# == iguales | != diferentes | <, >, <=, >= rango
#datos.query('edad == 29')
#datos.query('edad >= 29')
datos.query('edad == 17')

,encuesta,encuestador,sexo,edad,entidad,facultad,turno,tipo_transporte,gasto_transporte,gasto_comida,...,cercania_transporte,numero_transporte,promedio,actividad_extra,tiempo_descanso,ausencia_recursos,fuente_ingresos,frecuencia_retardos,apoyo_transporte,impacto_transporte
146,147,14,2,17,10,6,2,1,1,1,...,1,2,4,1,4,2,1,1,2,1
1070,1071,5,2,17,8,6,2,1,4,3,...,2,1,2,2,4,2,1,3,2,1
1256,1257,38,1,17,17,7,2,2,3,2,...,1,3,1,2,4,2,1,4,1,2
1498,1499,13,2,17,10,6,1,4,3,5,...,1,1,2,1,2,2,1,1,4,2

In [25]:
datos[datos['edad']==35]

,encuesta,encuestador,sexo,edad,entidad,facultad,turno,tipo_transporte,gasto_transporte,gasto_comida,...,cercania_transporte,numero_transporte,promedio,actividad_extra,tiempo_descanso,ausencia_recursos,fuente_ingresos,frecuencia_retardos,apoyo_transporte,impacto_transporte
52,53,14,2,35,4,2,3,3,1,4,...,1,3,4,1,2,2,2,2,2,2
595,596,36,1,35,4,7,3,1,1,5,...,2,2,4,1,3,2,2,2,1,1
758,759,44,1,35,17,7,3,4,3,5,...,1,1,3,1,4,2,1,1,1,2
1503,1504,43,2,35,4,11,2,3,4,3,...,1,2,3,1,4,1,1,3,2,1
1977,1978,43,1,35,4,10,2,2,1,5,...,2,1,3,2,4,2,3,1,1,2

In [26]:
# Filtrar datos de manera sencilla y explicita
datos.query('entidad == 9 and sexo == 2')

,encuesta,encuestador,sexo,edad,entidad,facultad,turno,tipo_transporte,gasto_transporte,gasto_comida,...,cercania_transporte,numero_transporte,promedio,actividad_extra,tiempo_descanso,ausencia_recursos,fuente_ingresos,frecuencia_retardos,apoyo_transporte,impacto_transporte
122,123,14,2,20,9,4,1,1,2,1,...,2,3,4,2,3,2,2,1,1,1
131,132,12,2,19,9,4,1,1,4,1,...,1,2,4,2,3,2,1,1,1,1
173,174,2,2,28,9,2,3,4,4,2,...,2,1,3,2,3,2,1,3,1,1
190,191,42,2,22,9,7,3,1,1,3,...,1,2,3,1,2,2,1,4,1,1
315,316,40,2,20,9,11,1,1,1,1,...,2,2,3,2,3,2,1,4,2,2
477,478,12,2,23,9,2,2,1,2,3,...,1,3,4,2,4,2,1,1,1,2
488,489,1,2,22,9,2,2,1,1,4,...,1,2,3,2,3,2,2,4,1,1
502,503,23,2,19,9,1,2,1,1,2,...,1,3,4,1,3,2,1,4,4,2
508,509,32,2,20,9,3,2,2,1,2,...,1,1,4,1,3,2,1,4,2,1
537,538,1,2,18,9,1,1,1,4,1,...,1,2,4,2,2,2,1,4,1,1
538,539,1,2,19,9,1,1,1,4,1,...,3,3,4,1,2,2,1,4,4,1
544,545,40,2,21,9,9,1,1,4,1,...,2,2,3,2,3,2,1,2,2,2
586,587,40,2,21,9,8,1,2,4,2,...,2,2,3,1,3,2,1,4,2,2
613,614,1,2,22,9,6,1,2,4,1,...,1,1,3,2,2,2,2,1,2,2
621,622,47,2,20,9,8,1,1,4,3,...,1,2,3,2,2,2,1,1,1,2
646,647,31,2,22,9,7,1,1,4,5,...,1,2,4,1,3,2,1,4,1,1
695,696,11,2,20,9,4,2,2,4,5,...,1,1,3,2,4,2,1,1,1,1
745,746,18,2,25,9,3,2,1,4,3,...,2,1,4,1,3,2,2,4,1,1
883,884,3,2,19,9,5,1,3,2,1,...,1,2,3,1,3,2,1,3,1,2
917,918,19,2,20,9,5,2,1,1,4,...,2,2,4,1,3,2,1,2,2,1
921,922,39,2,21,9,11,1,3,4,1,...,1,2,3,2,3,1,1,2,1,1
946,947,19,2,19,9,6,2,1,4,3,...,1,1,4,1,4,2,2,2,2,1
990,991,6,2,23,9,3,1,1,4,1,...,2,1,3,2,4,2,1,4,2,2
1003,1004,6,2,20,9,2,2,1,4,1,...,1,2,4,2,4,2,1,4,2,2
1037,1038,35,2,42,9,8,1,2,4,5,...,2,3,3,1,3,1,1,4,1,1
1077,1078,15,2,20,9,1,3,2,3,3,...,3,2,3,1,4,2,1,4,4,1
1088,1089,5,2,21,9,6,1,2,1,3,...,2,2,2,2,4,2,1,2,4,1
1099,1100,15,2,21,9,6,3,1,3,1,...,2,4,3,2,3,2,1,4,1,2
1121,1122,36,2,19,9,11,1,1,4,3,...,2,3,2,1,2,2,1,2,1,2
1250,1251,32,2,20,9,8,1,2,1,1,...,4,2,4,2,3,2,1,3,2,1
1315,1316,21,2,18,9,2,2,2,1,2,...,1,2,4,1,2,2,1,2,1,1
1380,1381,32,2,21,9,10,3,1,1,1,...,2,2,3,1,3,2,2,4,4,1
1408,1409,32,2,20,9,10,2,2,4,2,...,1,1,4,2,4,2,1,2,2,1
1426,1427,33,2,26,9,9,2,1,1,1,...,2,2,3,1,2,2,1,2,1,2
1488,1489,32,2,20,9,11,3,2,4,1,...,1,2,2,1,4,2,1,4,4,1
1496,1497,32,2,19,9,11,2,1,1,1,...,1,2,4,2,4,2,1,2,4,1
1534,1535,32,2,21,9,3,3,2,1,1,...,1,2,2,2,4,2,1,1,2,1
1558,1559,3,2,25,9,2,2,1,4,4,...,2,1,4,2,3,2,1,1,1,2
1569,1570,32,2,23,9,3,2,1,1,2,...,1,2,2,2,4,2,1,1,2,2
1573,1574,41,2,20,9,9,3,1,1,2,...,2,2,2,2,3,2,1,3,1,2
1575,1576,15,2,24,9,3,1,2,1,2,...,3,2,3,2,2,1,1,4,1,1
1640,1641,27,2,21,9,9,3,2,1,4,...,2,3,4,2,1,1,3,3,1,1
1678,1679,24,2,19,9,2,1,1,4,2,...,2,1,4,2,4,2,1,4,4,1
1686,1687,41,2,20,9,8,1,2,4,2,...,2,1,3,2,3,2,2,2,1,2
1742,1743,9,2,20,9,5,1,2,2,4,...,2,2,4,2,4,2,2,4,3,1
1765,1766,9,2,23,9,6,2,2,1,4,...,2,4,3,2,2,2,1,1,4,2
1806,1807,27,2,20,9,8,1,2,1,4,...,2,3,3,2,1,1,1,1,2,1
1952,1953,9,2,21,9,4,2,3,1,4,...,2,2,3,1,2,1,1,1,3,1
1968,1969,43,2,21,9,11,1,3,1,4,...,2,4,3,1,4,2,1,4,1,1
2016,2017,21,2,21,9,6,1,2,4,1,...,1,2,4,1,4,1,1,1,2,2

In [27]:
# Para graficar existen multiples librerias en este caso se usa plotly
import plotly.express as px

fig = px.histogram(x = datos.query('edad >= 17 and edad <= 30 and facultad == 11')['facultad'])

fig.show()

In [28]:
fig = px.scatter(datos, x = datos['entidad'], y = datos['edad'])
fig.show()

In [29]:
# Agrupar datos por condiciones
datos.groupby(['entidad', 'sexo']).agg(ConteoSexo=('sexo', 'count'), ConteoEntidad = ('entidad', 'count')).reset_index()

    entidad  sexo  ConteoSexo  ConteoEntidad
0         1     1          55             55
1         1     2          47             47
2         2     1          34             34
3         2     2          19             19
4         3     1          45             45
5         3     2          57             57
6         4     1         128            128
7         4     2         135            135
8         5     1          63             63
9         5     2          56             56
10        6     1          25             25
11        6     2          18             18
12        7     1         162            162
13        7     2         156            156
14        8     1          64             64
15        8     2          57             57
16        9     1          47             47
17        9     2          50             50
18       10     1         133            133
19       10     2         105            105
20       11     1          42             42
21       11     2          44             44
22       12     1          37             37
23       12     2          28             28
24       13     1          25             25
25       13     2          21             21
26       14     1          46             46
27       14     2          54             54
28       15     1          74             74
29       15     2          64             64
30       16     1          32             32
31       16     2          39             39
32       17     1          64             64
33       17     2          59             59